-- ====================================================================
-- Supabase/PostgreSQL Schema - Sistem Manajemen Perpustakaan
-- Migrasi dari database/schema.sql SQLite
-- ====================================================================

begin;

-- Supabase memakai PostgreSQL, jadi tidak perlu PRAGMA foreign_keys.
-- Foreign key aktif secara default di PostgreSQL.

-- ====================================================================
-- 1. TABEL USERS
-- ====================================================================
create table if not exists public.users (
    id_user  integer generated by default as identity primary key,
    username text not null unique,
    password text not null,
    role     text not null check (role in ('Admin', 'Petugas'))
);

create unique index if not exists idx_users_username_lower
    on public.users (lower(username));

-- ====================================================================
-- 2. TABEL KATEGORI
-- ====================================================================
create table if not exists public.kategori (
    id_kategori   integer generated by default as identity primary key,
    nama_kategori text not null unique
);

-- ====================================================================
-- 3. TABEL BUKU
-- ====================================================================
create table if not exists public.buku (
    id_buku     integer generated by default as identity primary key,
    judul       text not null,
    penulis     text not null,
    penerbit    text not null,
    tahun       integer not null check (tahun > 0),
    stok        integer not null default 0 check (stok >= 0),
    id_kategori integer references public.kategori(id_kategori)
);

create unique index if not exists idx_buku_judul_lower
    on public.buku (lower(judul));

create index if not exists idx_buku_id_kategori
    on public.buku (id_kategori);

-- ====================================================================
-- 4. TABEL ANGGOTA
-- ====================================================================
create table if not exists public.anggota (
    id_anggota   integer generated by default as identity primary key,
    nama         text not null,
    alamat       text,
    no_hp        text,
    foto_pdf_path text,
    status       text not null default 'Aktif'
                 check (status in ('Aktif', 'Tidak Aktif'))
);

create unique index if not exists idx_anggota_nama_lower
    on public.anggota (lower(nama));

-- ====================================================================
-- 5. TABEL PEMINJAMAN
-- ====================================================================
create table if not exists public.peminjaman (
    id_pinjam            integer generated by default as identity primary key,
    id_anggota           integer not null references public.anggota(id_anggota),
    tanggal_pinjam       text not null check (tanggal_pinjam ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
    tanggal_kembali      text not null check (tanggal_kembali ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
    tanggal_dikembalikan text check (tanggal_dikembalikan is null or tanggal_dikembalikan ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
    status               text not null default 'Dipinjam'
                         check (status in ('Dipinjam', 'Kembali', 'Terlambat', 'Hilang')),
    denda                numeric(12, 2) not null default 0 check (denda >= 0),
    check (tanggal_kembali >= tanggal_pinjam)
);

create index if not exists idx_peminjaman_id_anggota
    on public.peminjaman (id_anggota);

create index if not exists idx_peminjaman_status
    on public.peminjaman (status);

-- ====================================================================
-- 6. TABEL DETAIL_PEMINJAMAN
-- ====================================================================
create table if not exists public.detail_peminjaman (
    id_detail integer generated by default as identity primary key,
    id_pinjam integer not null references public.peminjaman(id_pinjam) on delete cascade,
    id_buku   integer not null references public.buku(id_buku),
    jumlah    integer not null default 1 check (jumlah > 0)
);

create index if not exists idx_detail_peminjaman_id_pinjam
    on public.detail_peminjaman (id_pinjam);

create index if not exists idx_detail_peminjaman_id_buku
    on public.detail_peminjaman (id_buku);

-- ====================================================================
-- DATA DUMMY
-- ====================================================================

insert into public.users (id_user, username, password, role) values
    (1, 'admin', 'admin123', 'Admin'),
    (2, 'petugas', 'petugas123', 'Petugas')
on conflict (username) do nothing;

insert into public.kategori (id_kategori, nama_kategori) values
    (1, 'Fiksi'),
    (2, 'Non-Fiksi'),
    (3, 'Sains & Teknologi'),
    (4, 'Sejarah'),
    (5, 'Pendidikan'),
    (6, 'Agama'),
    (7, 'Biografi')
on conflict (nama_kategori) do nothing;

insert into public.buku (id_buku, judul, penulis, penerbit, tahun, stok, id_kategori) values
    (1,  'Laskar Pelangi',           'Andrea Hirata',         'Bentang Pustaka', 2005, 5, 1),
    (2,  'Negeri 5 Menara',          'Ahmad Fuadi',           'Gramedia',        2009, 4, 1),
    (3,  'Bumi Manusia',             'Pramoedya Ananta Toer', 'Hasta Mitra',     1980, 3, 1),
    (4,  'Ayah',                     'Andrea Hirata',         'Bentang Pustaka', 2015, 6, 1),
    (5,  'Sapiens',                  'Yuval Noah Harari',     'KPG',             2014, 4, 2),
    (6,  'Atomic Habits',            'James Clear',           'Gramedia',        2018, 5, 2),
    (7,  'Clean Code',               'Robert C. Martin',      'Prentice Hall',   2008, 2, 3),
    (8,  'Artificial Intelligence',  'Stuart Russell',        'Erlangga',        2010, 3, 3),
    (9,  'Sejarah Indonesia Modern', 'M.C. Ricklefs',         'Serambi',         2001, 6, 4),
    (10, 'Sejarah Dunia',            'John M. Roberts',       'Alvabet',         2011, 4, 4),
    (11, 'Matematika SMA',           'Tim Penulis',           'Erlangga',        2020, 8, 5),
    (12, 'Biologi Molekular',        'Tim Peneliti',          'UI Press',        2019, 3, 5),
    (13, 'Al-Quran dan Ilmu',        'Zaghloul El-Naggar',    'Shorouk Int.',    2010, 5, 6),
    (14, 'Biografi Soekarno',        'Lambert Giebels',       'Grasindo',        2001, 4, 7),
    (15, 'Steve Jobs',               'Walter Isaacson',       'Gramedia',        2011, 3, 7)
on conflict do nothing;

insert into public.anggota (id_anggota, nama, alamat, no_hp, status) values
    (1, 'Budi Santoso',   'Jl. Merdeka No. 1, Jakarta',         '081234567890', 'Aktif'),
    (2, 'Siti Rahayu',    'Jl. Sudirman No. 5, Bandung',        '082345678901', 'Aktif'),
    (3, 'Ahmad Fauzi',    'Jl. Gatot Subroto No. 10, Surabaya', '083456789012', 'Aktif'),
    (4, 'Dewi Lestari',   'Jl. Diponegoro No. 15, Yogyakarta',  '084567890123', 'Aktif'),
    (5, 'Eko Prasetyo',   'Jl. Ahmad Yani No. 20, Semarang',    '085678901234', 'Tidak Aktif'),
    (6, 'Rini Wulandari', 'Jl. Kartini No. 8, Malang',          '086789012345', 'Aktif'),
    (7, 'Hendra Wijaya',  'Jl. Pahlawan No. 3, Medan',          '087890123456', 'Aktif'),
    (8, 'Fitri Amalia',   'Jl. Veteran No. 12, Makassar',       '088901234567', 'Aktif')
on conflict do nothing;

-- Sinkronkan sequence identity setelah insert id eksplisit.
select setval(pg_get_serial_sequence('public.users', 'id_user'), coalesce((select max(id_user) from public.users), 1));
select setval(pg_get_serial_sequence('public.kategori', 'id_kategori'), coalesce((select max(id_kategori) from public.kategori), 1));
select setval(pg_get_serial_sequence('public.buku', 'id_buku'), coalesce((select max(id_buku) from public.buku), 1));
select setval(pg_get_serial_sequence('public.anggota', 'id_anggota'), coalesce((select max(id_anggota) from public.anggota), 1));
select setval(pg_get_serial_sequence('public.peminjaman', 'id_pinjam'), coalesce((select max(id_pinjam) from public.peminjaman), 1));
select setval(pg_get_serial_sequence('public.detail_peminjaman', 'id_detail'), coalesce((select max(id_detail) from public.detail_peminjaman), 1));

-- ====================================================================
-- SUPABASE SECURITY
-- ====================================================================
-- Tabel berada di schema public yang dapat diekspos oleh Data API.
-- RLS dinyalakan agar data tidak otomatis terbuka untuk anon/authenticated API.
-- Aplikasi Java via JDBC memakai koneksi database langsung dan tidak membutuhkan
-- policy RLS. Jika nanti memakai Supabase REST API, tambahkan policy sesuai role.
alter table public.users enable row level security;
alter table public.kategori enable row level security;
alter table public.buku enable row level security;
alter table public.anggota enable row level security;
alter table public.peminjaman enable row level security;
alter table public.detail_peminjaman enable row level security;

commit;

-- ====================================================================
-- QUERY CEK
-- ====================================================================
-- select b.*, k.nama_kategori from public.buku b left join public.kategori k on b.id_kategori = k.id_kategori;
-- select p.*, a.nama from public.peminjaman p join public.anggota a on p.id_anggota = a.id_anggota where p.status = 'Dipinjam';
-- select b.judul, count(dp.id_detail) as total from public.detail_peminjaman dp join public.buku b on dp.id_buku = b.id_buku group by b.id_buku order by total desc;
